;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        isearch-abort
        isearch-delete-char
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        markdown-exdent-or-delete
        python-indent-dedent-line-backspace
        sgml-close-tag
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        count-words-region
        end-of-buffer
        goto-line
        ido-find-file
        ido-switch-buffer
        isearch-other-control-char
        mac-mwheel-scroll
        projectile-ack
        python-indent-electric-colon
        python-indent-shift-left
        query-replace
        ))
